export interface CategoryItem {
  id: string;
  name: string;
  icon: string; // Lucide icon name or emoji fallback
  color: string;
  bg: string;
  defaultIndivPrice: number;
  defaultGroupPrice: number;
  description: string;
}

export const Categories: CategoryItem[] = [
  {
    id: 'AC Service',
    name: 'AC Service',
    icon: 'wind',
    color: '#0284C7',
    bg: '#E0F2FE',
    defaultIndivPrice: 800,
    defaultGroupPrice: 550,
    description: 'Filter cleaning, gas top-up & cooling health check.',
  },
  {
    id: 'Appliance Repair',
    name: 'Appliance Repair',
    icon: 'wrench',
    color: '#D97706',
    bg: '#FEF3C7',
    defaultIndivPrice: 750,
    defaultGroupPrice: 450,
    description: 'Refrigerator, washing machine, microwave repairs.',
  },
  {
    id: 'Plumbing',
    name: 'Plumbing',
    icon: 'droplet',
    color: '#2563EB',
    bg: '#DBEAFE',
    defaultIndivPrice: 600,
    defaultGroupPrice: 380,
    description: 'Leak fixing, tap replacements, drainage inspection.',
  },
  {
    id: 'Electrical',
    name: 'Electrical',
    icon: 'zap',
    color: '#CA8A04',
    bg: '#FEF9C3',
    defaultIndivPrice: 550,
    defaultGroupPrice: 350,
    description: 'MCB switches, fan installation, chandelier fitting.',
  },
  {
    id: 'Carpenter',
    name: 'Carpenter',
    icon: 'hammer',
    color: '#9A3412',
    bg: '#FFEDD5',
    defaultIndivPrice: 700,
    defaultGroupPrice: 480,
    description: 'Furniture repair, door locks, modular kitchen touch-up.',
  },
  {
    id: 'Cleaning',
    name: 'Deep Cleaning',
    icon: 'sparkles',
    color: '#059669',
    bg: '#D1FAE5',
    defaultIndivPrice: 1200,
    defaultGroupPrice: 850,
    description: 'Bathroom, balcony, couch & full home deep cleaning.',
  },
  {
    id: 'Pest Control',
    name: 'Pest Control',
    icon: 'shield-alert',
    color: '#DC2626',
    bg: '#FEE2E2',
    defaultIndivPrice: 900,
    defaultGroupPrice: 600,
    description: 'Herbal cockroach, bedbug & mosquito control treatment.',
  },
  {
    id: 'Internet',
    name: 'Internet',
    icon: 'wifi',
    color: '#7C3AED',
    bg: '#EDE9FE',
    defaultIndivPrice: 1000,
    defaultGroupPrice: 700,
    description: 'Fiber broadband society bulk connection setup.',
  },
  {
    id: 'Moving',
    name: 'Moving & Packers',
    icon: 'truck',
    color: '#4B5563',
    bg: '#F3F4F6',
    defaultIndivPrice: 4500,
    defaultGroupPrice: 3200,
    description: 'Inter-city & local house shifting assistance.',
  },
  {
    id: 'Home Painting',
    name: 'Home Painting',
    icon: 'paint-bucket',
    color: '#DB2777',
    bg: '#FCE7F3',
    defaultIndivPrice: 3500,
    defaultGroupPrice: 2400,
    description: 'Interior wall painting, texture touch-up & waterproof.',
  },
  {
    id: 'RO Service',
    name: 'RO & Water Purifier',
    icon: 'filter',
    color: '#0891B2',
    bg: '#CFFAFE',
    defaultIndivPrice: 850,
    defaultGroupPrice: 580,
    description: 'Filter membrane replacement & water quality test.',
  },
  {
    id: 'CCTV',
    name: 'CCTV & Security',
    icon: 'video',
    color: '#475569',
    bg: '#E2E8F0',
    defaultIndivPrice: 1500,
    defaultGroupPrice: 1050,
    description: 'Balcony camera installation & Smart Door locks.',
  },
  {
    id: 'Other',
    name: 'Other Service',
    icon: 'grid',
    color: '#0F766E',
    bg: '#CCFBF1',
    defaultIndivPrice: 500,
    defaultGroupPrice: 350,
    description: 'Custom community group request.',
  },
];
